const html = require("../index.js");
const assert = require('assert');
const util = require('util');


var dummydata = "asdfjal;ksjf;lkasfaf";

function testtag1(tag, fc) {
    console.log("Testing: %s", tag);
    assert.strictEqual(fc(), util.format("<%s>", tag));
}
function testtag2(tag, fc) {
    console.log("Testing: %s", tag);
    assert.strictEqual(fc(dummydata), util.format("<%s>%s</%s>", tag, dummydata, tag));
}
var array2 = [
    ["A", html.a],
    ["ABBR", html.abbr],
    ["ADDRESS", html.address],
    ["ARTICLE", html.article],
    ["ASIDE", html.aside],
    ["AUDIO", html.audio],
    ["B", html.b],
    ["BDI", html.bdi],
    ["BDO", html.bdo],
    ["BLOCKQUOTE", html.blockquote],
    ["BODY", html.body],
    ["BUTTON", html.button],
    ["CANVAS", html.canvas],
    ["CAPTION", html.caption],
    ["CITE", html.cite],
    ["CODE", html.code],
    ["COLGROUP", html.colgroup],
    ["DATA", html.data],
    ["DATALIST", html.datalist],
    ["DD", html.dd],
    ["DEL", html.del],
    ["DETAILS", html.details],
    ["DFN", html.dfn],
    ["DIALOG", html.dialog],
    ["DIV", html.div],
    ["DL", html.dl],
    ["DT", html.dt],
    ["EM", html.em],
    ["FIELDSET", html.fieldset],
    ["FIGCAPTION", html.figcaption],
    ["FIGURE", html.figure],
    ["FOOTER", html.footer],
    ["FORM", html.form],
    ["H1", html.h1],
    ["H2", html.h2],
    ["H3", html.h3],
    ["H4", html.h4],
    ["H5", html.h5],
    ["H6", html.h6],
    ["HEAD", html.head],
    ["HEADER", html.header],
    ["HTML", html.html],
    ["I", html.i],
    ["IFRAME", html.iframe],
    ["INS", html.ins],
    ["KBD", html.kbd],
    ["LABEL", html.label],
    ["LEGEND", html.legend],
    ["LI", html.li],
    ["MAIN", html.main],
    ["MAP", html.map],
    ["MARK", html.mark],
    ["METER", html.meter],
    ["NAV", html.nav],
    ["NOSCRIPT", html.noscript],
    ["OBJECT", html.object],
    ["OL", html.ol],
    ["OPTGROUP", html.optgroup],
    ["OPTION", html.option],
    ["OUTPUT", html.output],
    ["P", html.p],
    ["PICTURE", html.picture],
    ["PRE", html.pre],
    ["PROGRESS", html.progress],
    ["Q", html.q],
    ["RB", html.rb],
    ["RP", html.rp],
    ["RT", html.rt],
    ["RTC", html.rtc],
    ["RUBY", html.ruby],
    ["S", html.s],
    ["SAMP", html.samp],
    ["SCRIPT", html.script],
    ["SECTION", html.section],
    ["SELECT", html.select],
    ["SMALL", html.small],
    ["SPAN", html.span],
    ["STRONG", html.strong],
    ["STYLE", html.style],
    ["SUB", html.sub],
    ["SUMMARY", html.summary],
    ["SUP", html.sup],
    ["TABLE", html.table],
    ["TBODY", html.tbody],
    ["TD", html.td],
    ["TEMPLATE", html.template],
    ["TEXTAREA", html.textarea],
    ["TFOOT", html.tfoot],
    ["TH", html.th],
    ["THEAD", html.thead],
    ["TIME", html.time],
    ["TITLE", html.title],
    ["TR", html.tr],
    ["U", html.u],
    ["UL", html.ul],
    ["VAR", html.var],
    ["VIDEO", html.video],

];
var array1 = [
    ["AREA", html.area],
    ["BASE", html.base],
    ["BR", html.br],
    ["COL", html.col],
    ["EMBED", html.embed],
    ["HR", html.hr],
    ["IMG", html.img],
    ["INPUT", html.input],
    ["LINK", html.link],
    ["META", html.meta],
    ["PARAM", html.param],
    ["SOURCE", html.source],
    ["TRACK", html.track],
    ["WBR", html.wbr],
];
array2.forEach((v) => {
    testtag2(v[0], v[1]);
});
array1.forEach((v) => {
    testtag1(v[0], v[1]);
});
